### ISSUE TITLE
Trait

### ISSUE THREAD

**Issue by cardi777** [chaseconey/laravel-activity#1]
maybe im just new to this, but i keep getting the following:

Trait 'matting\RecordsActivity' not found (matting being my namespace)

I have followed your instructions perfectly.

**Comment by chaseconey** [comment]
Sorry for the slow response - didn't get a notification for some reason.

It sounds like you simply need to add a "use" statement at the top of the class that you are utilizing the trait in.

It should look like this:

``` php

  use Chaseconey\ActivityRecorder\RecordsActivity;

  Class Tweet extends Model
  {
    use RecordsActivity;
  }

```

Let me know if that works!

**Comment by chaseconey** [comment]
I updated the README to display this information as well. Thanks for pointing that out.

**Comment by chaseconey** [comment]
@cardi777 Does this solve the problem for you?

**Comment by cardi777** [comment]
I'll let you know. Have to reinstall, I had given up :)

On Thu, 2 Jul 2015 11:40 pm Chase Coney notifications@github.com wrote:

> @cardi777 https://github.com/cardi777 Does this solve the problem for
> you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chaseconey/laravel-activity/issues/1#issuecomment-118036748
> .
> 
> ## 

Cheers,
Doug

**Comment by cardi777** [comment]
ok i think we are good :)

**Comment by chaseconey** [comment]
Ok cool - glad it was that easy!

**Comment by cardi777** [comment]
i love this plugin, its perfect for what i want.
