### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cardi777** [chaseconey/laravel-activity#4]
is it possible to make it work for non-auth users? If i could make the user_id not required, that would probably do it.

**Comment by chaseconey** [comment]
So for whatever reason I never got a notification for this :(.

At this time, I don't have any plans to support non-user actions. The main reason to support auditing for the apps that I have created in the past was to make sure a user couldn't do something without it being logged somewhere. That's not to say you couldn't take the package and modify it to support your specific needs.
